### ISSUE TITLE
ebuild of app-editors/vscode-bin have problem with missing required dependencies of libnss and libcups

### ISSUE THREAD

**Issue by zendet** [bombo82/bombo82-overlay#17]
your .eduild doesn't have required dependensies. you can try to start vscode-bin without these two deps, but you will get this line of negative speech
`/opt/vscode-bin/bin/../code: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory` (same with libcups)
[jorgicio](https://github.com/jorgicio/jorgicio-gentoo-overlay/issues/126) had an identical problem with these deps, i think you can easily use his solution ;)

**Comment by bombo82** [comment]
Hi, thank you for reporting the error.
I fixed the dependencies and it should now work fine.

Forgive the delay, I manage this repository in my spare rime and sometimes I am not very responsive :-(
