### ISSUE TITLE
Package request

### ISSUE THREAD

**Issue by Nuralii1i** [bombo82/bombo82-overlay#19]
Thanks for sharing your ebuild repo
JetBrains released the [RustRover](https://www.jetbrains.com/rust) ide for Rust developers(Preview Edition of course)
Do you have any plans (and extra time) to write an ebuild for it?(I looked around the GPO website,nobody did it yet,I also am a beginner to Gentoo......So)
I would be immensely grateful for it

**Comment by Blackburn29** [comment]
> Thanks for sharing your ebuild repo JetBrains released the [RustRover](https://www.jetbrains.com/rust) ide for Rust developers(Preview Edition of course) Do you have any plans (and extra time) to write an ebuild for it?(I looked around the GPO website,nobody did it yet,I also am a beginner to Gentoo......So) I would be immensely grateful for it

I added this IDE to my overlay if youre interested.

https://github.com/Blackburn29/blackburn29-overlay/tree/master/dev-util/rustrover

**Comment by bombo82** [comment]
Forgive me for the delay in reponding and adding the package.
The addition had been planned, but I had a little time to dedicate to this overlay in the past few months.
