### ISSUE TITLE
Vmware modules compile error (fatal error: linux/frame.h: No such file or directory)

### ISSUE THREAD

**Issue by mt190502** [bombo82/bombo82-overlay#5]
Hello. I compiling vmware on this overlay. But emerge is giving this fail. 

" fatal error: linux/frame.h: No such file or directory "

How can i solve this problem? Thanks

![image](https://user-images.githubusercontent.com/62564400/102341411-da08d680-3fa8-11eb-8a63-fdcfda8970bf.png)

**Comment by bombo82** [comment]
Hi @MuhammedTaha02,
the missing file is one of the Linux kernel source files, so I think the problem is related to the kernel package you are using.

What package and kernel version are you installed?

**Comment by mt190502** [comment]
> Hi @MuhammedTaha02,
> the missing file is one of the Linux kernel source files, so I think the problem is related to the kernel package you are using.
> 
> What package and kernel version are you installed?

I am using this kernel version;
5.10.1-gentoo-x86_64

I installed Vmware with the command.
sudo emerge --ask app-emulation/vmware-workstation acct-group/vmware app-emulation/vmware-modules

**Comment by bombo82** [comment]
I just updated the "vmware-modules" package to support the 5.10 kernel.

Please, try again with the new version and let me know if it works.

**Comment by mt190502** [comment]
> I just updated the "vmware-modules" package to support the 5.10 kernel.
> 
> Please, try again with the new version and let me know if it works.

Problem is solved. Thanks :)

>>> Emerging (2 of 5) app-emulation/vmware-modules-16.1.0::bombo82
>>> Installing (2 of 5) app-emulation/vmware-modules-16.1.0::bombo82
>>> Recording app-emulation/vmware-modules in "world" favorites file...
