### ISSUE TITLE
bug: Could not open /dev/vmmon: No such file or directory 

### ISSUE THREAD

**Issue by ghost** [bombo82/bombo82-overlay#6]
I have been trying to solve the problem for a long time and everything is in vain

when starting the virtual machine, I get the error `Could not open /dev/vmmon: No such file or directory`.

Kernel 5.4, openrc, and recompiled https://github.com/mkubecek/vmware-host-modules for my kernel

**Comment by bombo82** [comment]
Forgive me for the delay in replying.

When you install `vmware-workstation` from this repository, it automatically installs the `vmware-modules` package as a dependency.
You don't need to take any other action. The link you provided is outdated (workstation version 14), and probably these instructions do not work with workstation 16. The workstation and module versions are strictly related.

vmware-workstation package comes with an init script that loads those kernel modules. You should start the init script called "vmware" and add it to the default runlevel.

**Comment by ghost** [comment]
@bombo82 
Thanks for the answer.
I have suggestions that I am having problems with Gentoo. I will try to test it on another machine and give an answer.

**Comment by bombo82** [comment]
Hi @Bittyby
You have made progress on your test?
